import AppKit
import Foundation
import Network
import SwiftUI
import Testing
@testable import Rapid

/// Which code blocks offer a preview, and what the preview is drawn at.
///
/// The rendering itself is AppKit's, so what is worth testing is the two
/// judgements around it: whether a block is an SVG document at all, and how a
/// document with no natural pixel size is fitted to a column.
@Suite("SVG preview")
struct SVGPreviewTests {

    private let svg = """
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
          <circle cx="50" cy="50" r="40" fill="#3b82f6"/>
        </svg>
        """

    // MARK: - What counts as previewable

    @Test("An SVG document is offered a preview", arguments: [
        "svg", "xml", "html", "SVG", nil,
    ])
    func svgIsPreviewable(_ language: String?) {
        #expect(SVGPreview.looksLikeSVG(code: svg, language: language))
    }

    /// Prose or source that merely mentions the string is about SVG, not SVG.
    ///
    /// Every case here carries a language the filter *accepts*, so the
    /// open-with-a-tag rule is the only thing that can reject them. An earlier
    /// version of this test used `swift` and `markdown` tags, which a language
    /// allowlist also rejected — so deleting either guard left it green and it
    /// proved nothing about either.
    @Test("Code that only mentions SVG is not previewable", arguments: [
        #"let markup = "<svg viewBox=\"0 0 10 10\"/>""#,
        "Here is the diagram: <svg viewBox=\"0 0 10 10\"/>",
        "# How to draw an <svg> by hand",
    ])
    func mentioningSVGIsNotEnough(_ code: String) {
        #expect(!SVGPreview.looksLikeSVG(code: code, language: "xml"))
    }

    /// A mis-tagged document still previews. Models label SVG as whatever
    /// they feel like, and refusing on the tag would hide a working preview.
    @Test("A mis-tagged document is still previewable")
    func misTaggedIsStillPreviewable() {
        #expect(SVGPreview.looksLikeSVG(code: svg, language: "python"))
    }

    @Test("A self-closing SVG root is complete enough to attempt")
    func selfClosingRootIsPreviewable() {
        #expect(SVGPreview.looksLikeSVG(code: #"<svg viewBox="0 0 10 10"/>"#, language: nil))
    }

    /// Once `<svg` arrives, streaming can flush hundreds of times before the
    /// closing root. None of those partial states should synchronously invoke
    /// AppKit's parser on the main thread.
    @Test("An incomplete SVG is not ready for parsing")
    func incompleteRootIsNotPreviewable() {
        #expect(!SVGPreview.looksLikeSVG(
            code: #"<svg viewBox="0 0 10 10"><path d="M0 0""#,
            language: "svg"
        ))
    }

    @Test("Closing-root text in non-markup does not finish a stream", arguments: [
        "<svg><!-- </svg> -->",
        "<svg><![CDATA[</svg>]]>",
        #"<svg data-example="</svg>">"#,
    ])
    func fakeClosingRootIsIgnored(_ code: String) {
        #expect(!SVGPreview.looksLikeSVG(code: code, language: "svg"))
    }

    @Test("A real closing root after ignored text finishes the stream")
    func closingRootAfterCommentIsAccepted() {
        let code = "<svg><!-- </svg> --><text>ok</text></svg>"
        #expect(SVGPreview.looksLikeSVG(code: code, language: "svg"))
    }

    @Test("A self-closing nested SVG does not hide the outer closing root")
    func nestedSelfClosingSVGIsAccepted() {
        #expect(SVGPreview.looksLikeSVG(code: "<svg><svg/></svg>", language: "svg"))
    }

    @Test("XML wrappers around the SVG root are accepted", arguments: [
        #"<?xml version="1.0"?><svg viewBox="0 0 1 1"/>"#,
        "<svg></svg><!-- generated -->",
        "<svg></svg><!-- example: </svg> -->",
        "<svg></svg><?generated by=tool?>",
        "<svg></svg   >",
    ])
    func xmlWrappersAreAccepted(_ code: String) {
        #expect(SVGPreview.looksLikeSVG(code: code, language: "svg"))
    }

    @Test("Long trailing XML trivia does not hide a completed root")
    func longTrailingCommentIsAccepted() {
        let code = "<svg></svg><!--" + String(repeating: " generated", count: 300) + " -->"
        #expect(SVGPreview.looksLikeSVG(code: code, language: "svg"))
    }

    @Test("Nothing to preview", arguments: [
        "", "   ", "print(\"hello\")", "<html><body>hi</body></html>",
    ])
    func nonSVGIsNotPreviewable(_ code: String) {
        #expect(!SVGPreview.looksLikeSVG(code: code, language: nil))
    }

    /// The parse is synchronous on the main thread, and a model can emit a
    /// megabyte of path data.
    @Test("An oversized document is refused before parsing")
    func oversizedIsRefused() {
        let huge = "<svg>" + String(repeating: "x", count: SVGPreview.maximumSourceBytes) + "</svg>"
        #expect(!SVGPreview.looksLikeSVG(code: huge, language: "svg"))
    }

    @MainActor
    @Test("An excessively nested document is refused")
    func excessivelyNestedDocumentIsRejected() {
        let code = "<svg>" + String(repeating: "<g>", count: 65)
            + String(repeating: "</g>", count: 65) + "</svg>"
        #expect(SVGPreview.image(from: code) == nil)
    }

    // MARK: - Rendering

    @MainActor
    @Test("A valid document renders")
    func validDocumentRenders() {
        let image = SVGPreview.image(from: svg)
        #expect(image != nil)
        #expect(image?.size == CGSize(width: 100, height: 100))
    }

    /// The usual mid-stream state: the fence has not closed and the document
    /// is half-written. Nil, so the button never appears for it.
    @MainActor
    @Test("An incomplete or broken document renders nothing", arguments: [
        #"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><circ"#,
        "<svg",
        "not markup at all",
        "",
    ])
    func brokenDocumentRendersNothing(_ code: String) {
        #expect(SVGPreview.image(from: code) == nil)
    }

    @MainActor
    @Test("Resource-bearing and expensive SVG constructs are refused", arguments: [
        #"<svg><image href="https://example.com/a.png"/></svg>"#,
        #"<svg><image href="data:image/png;base64,AA=="/></svg>"#,
        #"<svg><style>@import url(https://example.com/a.css)</style></svg>"#,
        #"<svg><filter id="f"><feGaussianBlur stdDeviation="9"/></filter></svg>"#,
        #"<svg><script>alert(1)</script></svg>"#,
        #"<!DOCTYPE svg [<!ENTITY x "boom">]><svg><text>&x;</text></svg>"#,
        #"<?xml-stylesheet href="https://example.com/a.css"?><svg/>"#,
        #"<svg><rect fill="u\72l(h\74tp\3a\2f\2fexample.com/a)"/></svg>"#,
        #"<svg><rect fill="url(#safe) url(https://example.com/a)"/></svg>"#,
    ])
    func unsafeConstructsRenderNothing(_ code: String) {
        #expect(SVGPreview.image(from: code) == nil)
    }

    @MainActor
    @Test("Quoted local CSS fragment references remain safe")
    func quotedLocalCSSURLRenders() {
        let code = #"<svg width="10" height="10"><defs><linearGradient id="g"/></defs><rect width="10" height="10" fill="url('#g')"/></svg>"#
        #expect(SVGPreview.image(from: code) != nil)
    }

    // MARK: - Fitting a vector to a column

    @Test("A large document is scaled down to the column")
    func largeIsScaledToColumn() {
        let size = SVGPreview.drawSize(for: CGSize(width: 800, height: 400), inWidth: 400)
        #expect(size == CGSize(width: 400, height: 200))
    }

    /// A 24-point icon blown across a 700-point column reads as a mistake
    /// rather than as a preview.
    @Test("A small document is not blown up")
    func smallIsNotUpscaled() {
        let size = SVGPreview.drawSize(for: CGSize(width: 24, height: 24), inWidth: 700)
        #expect(size == CGSize(width: 24, height: 24))
    }

    @Test("A very tall document is capped rather than filling the transcript")
    func tallIsCapped() {
        let size = SVGPreview.drawSize(for: CGSize(width: 100, height: 4_000), inWidth: 400)
        #expect(size.height <= SVGPreview.maximumHeight)
        // Aspect is kept while capping.
        #expect(abs(size.width / size.height - 100.0 / 4_000.0) < 0.01)
    }

    /// Independent integral rounding used to collapse the short dimension to
    /// zero, leaving the button in Preview mode while the source still drew.
    @Test("An extreme aspect ratio keeps both dimensions drawable")
    func extremeAspectRatioStaysDrawable() {
        let size = SVGPreview.drawSize(for: CGSize(width: 1, height: 4_000), inWidth: 400)
        #expect(size.width > 0)
        #expect(size.height == SVGPreview.maximumHeight)
    }

    @Test("Degenerate sizes produce nothing to draw", arguments: [
        CGSize(width: 0, height: 100), CGSize(width: 100, height: 0), CGSize.zero,
    ])
    func degenerateSizes(_ imageSize: CGSize) {
        #expect(SVGPreview.drawSize(for: imageSize, inWidth: 400) == .zero)
    }

    @Test("A zero-width column produces nothing to draw")
    func zeroWidthColumn() {
        #expect(SVGPreview.drawSize(for: CGSize(width: 100, height: 100), inWidth: 0) == .zero)
    }
}

/// The properties of AppKit's own SVG support this feature is built on.
///
/// These are not testing Apple's code for its own sake — each one is a claim
/// the design rests on, and if any stops holding, the right response is a
/// different design rather than a patch.
@MainActor
@Suite("SVG rendering and input-safety assumptions")
struct AppKitSVGAssumptionTests {

    /// Vector, not a bitmap at the document's nominal size. If this became an
    /// upscale, a preview on a Retina display would be visibly soft and the
    /// feature would need a real renderer.
    @Test("The document re-rasterises at the size it is drawn")
    func rendersAsVector() throws {
        let triangle = """
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
              <path d="M0 0 L10 10 L0 10 Z" fill="black"/>
            </svg>
            """
        let image = try #require(SVGPreview.image(from: triangle))

        func edgeWidth(at pixels: Int) -> Int {
            let rep = NSBitmapImageRep(
                bitmapDataPlanes: nil, pixelsWide: pixels, pixelsHigh: pixels,
                bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
                colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0
            )!
            NSGraphicsContext.saveGraphicsState()
            NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
            image.draw(in: NSRect(x: 0, y: 0, width: CGFloat(pixels), height: CGFloat(pixels)))
            NSGraphicsContext.restoreGraphicsState()
            #expect(rep.colorAt(x: 1, y: pixels / 2)?.alphaComponent ?? 0 > 0.9)
            #expect(rep.colorAt(x: pixels - 2, y: pixels / 2)?.alphaComponent ?? 1 < 0.05)
            return (0..<pixels).count {
                guard let colour = rep.colorAt(x: $0, y: pixels / 2) else { return false }
                return colour.alphaComponent > 0.05 && colour.alphaComponent < 0.95
            }
        }
        // An upscaled 10pt bitmap would smear this edge across many pixels at
        // 512; a vector re-rasterise keeps it at one.
        #expect(edgeWidth(at: 64) <= 2)
        #expect(edgeWidth(at: 512) <= 2)
    }

    /// The validator boundary that makes this feature safe enough to ship
    /// without a sandbox: model-authored resource references are rejected
    /// before AppKit receives them.
    ///
    /// If this ever starts fetching, a model could exfiltrate the transcript
    /// through an `<image>` URL, and the feature would need a network policy.
    @Test("An external reference is rejected without a network request")
    func remoteReferenceIsNotFetched() async throws {
        let probe = try #require(LocalRequestProbe())
        defer { probe.stop() }
        #expect(probe.recordControlConnection(), "the listener did not observe its positive control")
        let baseline = probe.requestCount
        let svg = """
            <svg xmlns="http://www.w3.org/2000/svg" \
            xmlns:xlink="http://www.w3.org/1999/xlink" \
            viewBox="0 0 100 100" width="100" height="100">
              <use xlink:href="http://127.0.0.1:\(probe.port)/leak.svg#shape"/>
            </svg>
            """
        #expect(SVGPreview.image(from: svg) == nil, "external resources must be rejected")

        // A second known connection is a deterministic barrier through the
        // listener after drawing. Exactly one new request must be the control;
        // any renderer request makes the delta larger.
        #expect(probe.recordControlConnection(), "the listener lost its control connection")
        try await Task.sleep(for: .milliseconds(100))
        #expect(probe.requestCount == baseline + 1, "the SVG renderer reached the network")
    }
}

/// A loopback listener that counts inbound connections.
///
/// Deliberately not an HTTP server: the assertion is "nothing connected at
/// all", and accepting the socket is already enough to know that something
/// did. Keeping it to a listener means the test cannot be fooled by a reply
/// it wrote itself.
final class LocalRequestProbe: @unchecked Sendable {
    private let listener: NWListener
    private let counter: Counter
    let port: UInt16

    var requestCount: Int { counter.value }

    /// The count lives in its own object so the connection handler can be
    /// installed **before** `start()` without capturing a half-initialised
    /// `self`. That ordering is not a style preference: `NWListener` requires
    /// `newConnectionHandler` to be set before the listener starts, and an
    /// earlier version of this class installed it afterwards to dodge a
    /// compiler complaint about `self.port`. It never fired, so every
    /// `requestCount == 0` assertion built on it passed for the wrong reason.
    /// The positive control in `MermaidNetworkDenialTests` exists to make
    /// that failure loud rather than silent.
    private final class Counter: @unchecked Sendable {
        private let lock = NSLock()
        private var count = 0
        private var controls: [String: DispatchSemaphore] = [:]
        var value: Int {
            lock.lock()
            defer { lock.unlock() }
            return count
        }
        func increment() {
            lock.lock()
            count += 1
            lock.unlock()
        }
        func registerControl(_ token: String) -> DispatchSemaphore {
            let observed = DispatchSemaphore(value: 0)
            lock.lock()
            controls[token] = observed
            lock.unlock()
            return observed
        }
        func acknowledgeControl(_ token: String) {
            lock.lock()
            let observed = controls.removeValue(forKey: token)
            lock.unlock()
            observed?.signal()
        }
    }

    /// Make a known loopback connection and wait until the listener handler
    /// has counted it. This proves the negative assertion is observing a live
    /// listener and provides an ordering barrier after the image draw.
    func recordControlConnection() -> Bool {
        let token = UUID().uuidString
        let observed = counter.registerControl(token)
        let ready = DispatchSemaphore(value: 0)
        let connection = NWConnection(
            host: .ipv4(.loopback), port: NWEndpoint.Port(rawValue: port)!, using: .tcp
        )
        connection.stateUpdateHandler = { state in
            switch state {
            case .ready, .failed: ready.signal()
            default: break
            }
        }
        connection.start(queue: .global())
        guard ready.wait(timeout: .now() + 2) == .success else {
            connection.cancel()
            return false
        }
        connection.send(content: Data("CONTROL:\(token)".utf8), completion: .contentProcessed { _ in })
        let acknowledged = observed.wait(timeout: .now() + 2) == .success
        connection.cancel()
        return acknowledged
    }

    init?() {
        let counter = Counter()
        let parameters = NWParameters.tcp
        parameters.requiredLocalEndpoint = .hostPort(host: .ipv4(.loopback), port: .any)
        guard let listener = try? NWListener(using: parameters) else { return nil }
        self.listener = listener
        self.counter = counter

        listener.newConnectionHandler = { connection in
            counter.increment()
            connection.start(queue: .global())
            // `CONTROL:` plus a canonical UUID is exactly 44 UTF-8 bytes, so
            // do not acknowledge a partial TCP receive as the control.
            connection.receive(minimumIncompleteLength: 44, maximumLength: 44) {
                data, _, _, _ in
                if let data,
                   let message = String(data: data, encoding: .utf8),
                   message.hasPrefix("CONTROL:") {
                    counter.acknowledgeControl(String(message.dropFirst("CONTROL:".count)))
                }
                connection.cancel()
            }
        }

        let ready = DispatchSemaphore(value: 0)
        listener.stateUpdateHandler = { state in
            switch state {
            case .ready, .failed: ready.signal()
            default: break
            }
        }
        listener.start(queue: .global())
        guard ready.wait(timeout: .now() + 2) == .success,
              let resolved = listener.port?.rawValue else {
            listener.cancel()
            return nil
        }
        port = resolved
    }

    func stop() { listener.cancel() }
}

/// Which way up the picture is.
///
/// This exists because it shipped wrong. `MarkdownCodeBlockView` is
/// `isFlipped`, and `NSImage.draw(in:)` — the short overload — does not
/// compensate, so every preview was painted upside down and mirrored. Twenty
/// tests passed while it was broken: they asked whether an image existed,
/// what size it was, and how tall the card became, and not one of them looked
/// at the pixels.
@MainActor
@Suite("Preview orientation")
struct PreviewOrientationTests {

    /// Red across the top, blue across the bottom. Any flip swaps them.
    private let banded = """
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
          <rect x="0" y="0" width="100" height="50" fill="#ff0000"/>
          <rect x="0" y="50" width="100" height="50" fill="#0000ff"/>
        </svg>
        """

    @Test("The preview is drawn the right way up")
    func previewIsNotFlipped() throws {
        let options = MarkdownOptions()
        let view = MarkdownCodeBlockView(options: options)
        view.frame = NSRect(x: 0, y: 0, width: 300, height: 400)
        view.configure(code: banded, language: "svg", options: options)

        // No press: a renderable document now opens as its picture.
        view.frame.size.height = view.height(forWidth: 300)

        let rep = try #require(view.bitmapImageRepForCachingDisplay(in: view.bounds))
        view.cacheDisplay(in: view.bounds, to: rep)

        // Sample inside the picture, not at the card's midpoint: a 100pt
        // document is never upscaled, so it occupies the left of a 300pt card
        // and the centre column misses it entirely. Convert points using the
        // cache representation's actual scale (1x and 2x are both possible).
        let pixelScale = CGFloat(rep.pixelsWide) / view.bounds.width
        let column = Int((options.codeInsets.leading + 50) * pixelScale)

        // Red is the document's top band, so it has to appear above blue.
        func firstRow(where matches: (NSColor) -> Bool) -> Int? {
            (0..<rep.pixelsHigh).first { y in
                guard let colour = rep.colorAt(x: column, y: y) else { return false }
                return matches(colour)
            }
        }
        let red = try #require(
            firstRow { $0.redComponent > 0.7 && $0.blueComponent < 0.3 },
            "no red band found — the preview did not draw"
        )
        let blue = try #require(
            firstRow { $0.blueComponent > 0.7 && $0.redComponent < 0.3 },
            "no blue band found — the preview did not draw"
        )
        // `NSBitmapImageRep` numbers rows from the top: row 0 is the visual
        // top of the card, whatever the source view's `isFlipped` says. So an
        // upright picture puts red — the document's top band — at the smaller
        // row index. `rowOrderIsTopDown` below pins this, because believing
        // the opposite is exactly how the preview shipped upside down.
        #expect(red < blue, "the preview is upside down: blue (bottom of the document) drew above red")
    }

    /// Which end of an `NSBitmapImageRep` is the top.
    ///
    /// The orientation test above is only as good as its idea of row order,
    /// and a wrong idea there is invisible: it makes the assertion demand the
    /// bug. That happened — the row order was asserted from memory as
    /// bottom-up, the expectation was inverted to match, and two rounds of
    /// "fixes" then chased the inverted test by adding a second flip. So the
    /// premise gets measured against a picture drawn with no flipping at all.
    @Test("Bitmap rows are numbered from the top")
    func rowOrderIsTopDown() throws {
        let image = try #require(NSImage(data: Data(banded.utf8)))
        let canvas = NSImage(size: CGSize(width: 100, height: 100))
        canvas.lockFocus()
        image.draw(in: CGRect(x: 0, y: 0, width: 100, height: 100))
        canvas.unlockFocus()
        let tiff = try #require(canvas.tiffRepresentation)
        let rep = try #require(NSBitmapImageRep(data: tiff))

        let top = try #require(rep.colorAt(x: 50, y: 0))
        let bottom = try #require(rep.colorAt(x: 50, y: rep.pixelsHigh - 1))
        #expect(top.redComponent > 0.7, "row 0 is not the document's red top band")
        #expect(bottom.blueComponent > 0.7, "the last row is not the document's blue bottom band")
    }
}

/// The wiring: does the button appear, and does the card grow when it is
/// pressed. The drawing itself is AppKit's, but the row height is ours — and
/// a preview the block stack has not made room for is a preview drawn over
/// whatever comes next.
@MainActor
@Suite("SVG preview in a code block")
struct MarkdownCodeBlockPreviewTests {

    private let svg = """
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 50" width="100" height="50">
          <rect width="100" height="50" fill="teal"/>
        </svg>
        """

    private func block(_ code: String, _ language: String?) -> MarkdownCodeBlockView {
        let view = MarkdownCodeBlockView(options: MarkdownOptions())
        view.frame = NSRect(x: 0, y: 0, width: 400, height: 200)
        view.configure(code: code, language: language, options: MarkdownOptions())
        return view
    }

    private func previewButton(in view: NSView) -> NSButton? {
        view.subviews.compactMap { $0 as? NSButton }
            .first { $0.accessibilityIdentifier() == "CodeBlock.Preview" }
    }

    @Test("A Swift block offers no preview")
    func swiftBlockHasNoButton() {
        let view = block("print(\"hi\")", "swift")
        #expect(previewButton(in: view)?.isHidden == true)
    }

    /// An untagged fence still reserves room for the button.
    ///
    /// `looksLikeSVG` ignores the language tag, so an untagged ``` block
    /// holding an SVG gets a Preview button — but `headerHeight` used to
    /// return zero without a tag, so the button was laid out over the card's
    /// own content with nothing behind it. Once the picture is wide enough to
    /// reach the top right, it paints underneath Preview and Copy.
    @Test("An untagged fence reserves the same header as a tagged one")
    func untaggedFenceReservesTheHeader() {
        let tagged = block(svg, "svg")
        let untagged = block(svg, nil)
        #expect(untagged.height(forWidth: 400) == tagged.height(forWidth: 400))
    }

    @Test("An invalid untagged document does not reserve an empty header")
    func invalidUntaggedDocumentHasNoHeader() {
        let code = "<svg><broken></svg>"
        let invalid = block(code, nil)
        let options = MarkdownOptions()
        let renderer = MarkdownTextRenderer(options: options)
        renderer.setCode(code, language: nil)
        let contentWidth = 400 - options.codeInsets.leading - options.codeInsets.trailing
        let expectedHeight = options.codeInsets.top
            + renderer.measureHeight(width: contentWidth) + options.codeInsets.bottom
        #expect(previewButton(in: invalid)?.isHidden == true)
        #expect(invalid.height(forWidth: 400) == expectedHeight)
    }

    @Test("An SVG block offers a preview")
    func svgBlockHasButton() {
        let view = block(svg, "svg")
        #expect(previewButton(in: view)?.isHidden == false)
    }

    /// Mid-stream the document is half-written. Offering a button that would
    /// render nothing is worse than offering none.
    @Test("A half-streamed document offers no preview yet")
    func partialDocumentHasNoButton() {
        let view = block("<svg xmlns=\"http://www.w3.org/2000/svg\"><rect wid", "svg")
        #expect(previewButton(in: view)?.isHidden == true)
    }

    /// The load-bearing one: the block stack lays rows out from
    /// `height(forWidth:)`, so a card whose body changed but whose height did
    /// not is a card drawn over whatever comes next.
    ///
    /// Preview is a *mode*. Two documents with the same `viewBox` but wildly
    /// different source lengths must preview at the same height — that is
    /// true only if the picture replaced the source, and false for any
    /// implementation that appends it.
    @Test("The preview replaces the source rather than stacking under it")
    func previewReplacesSource() throws {
        let padded = svg.replacingOccurrences(
            of: "<rect", with: String(repeating: "<!-- padding -->\n  ", count: 20) + "<rect"
        )
        let short = block(svg, "svg")
        let long = block(padded, "svg")

        // Both open as their picture, so both are already the image's height.
        #expect(short.height(forWidth: 400) == long.height(forWidth: 400))

        // Pressing shows each source, and only then do their heights diverge.
        for view in [short, long] {
            let button = try #require(previewButton(in: view))
            _ = button.target?.perform(button.action, with: button)
        }
        let shortSource = short.height(forWidth: 400)
        let longSource = long.height(forWidth: 400)
        #expect(longSource > shortSource, "the padded document should have a taller source")

        // And back to the picture, where they agree again — which is only true
        // if the picture replaced the source rather than joining it.
        for view in [short, long] {
            let button = try #require(previewButton(in: view))
            _ = button.target?.perform(button.action, with: button)
        }
        #expect(short.height(forWidth: 400) == long.height(forWidth: 400))
        #expect(long.height(forWidth: 400) < longSource)
    }

    /// A renderable document opens as its picture, so the button starts by
    /// offering the source.
    @Test("The button names the mode it switches to")
    func buttonTitleTracksState() throws {
        let view = block(svg, "svg")
        let button = try #require(previewButton(in: view))
        #expect(button.title == "Code")
        _ = button.target?.perform(button.action, with: button)
        #expect(button.title == "Preview")
    }

    /// Re-configuring with a different language — which happens on every
    /// streaming flush — must not leave a preview open on a block that is no
    /// longer an SVG.
    @Test("A block that stops being an SVG closes its preview")
    func previewClosesWhenNoLongerSVG() throws {
        let view = block(svg, "svg")
        let button = try #require(previewButton(in: view))
        let expanded = view.height(forWidth: 400)

        view.configure(code: "print(\"hi\")", language: "swift", options: MarkdownOptions())
        #expect(button.isHidden)
        #expect(view.height(forWidth: 400) < expanded)
        // Exactly a fresh block's height — not merely "shorter than before".
        // A leaked `isShowingPreview` still reserves the image's 50 points,
        // and the swift body being shorter than the SVG's would hide that
        // behind a passing inequality.
        let fresh = block("print(\"hi\")", "swift")
        #expect(view.height(forWidth: 400) == fresh.height(forWidth: 400))
    }
}

/// The layout chain, driven through a real SwiftUI host.
///
/// `togglePreview` flips internal state and calls
/// `invalidateIntrinsicContentSize()` from an AppKit button action, with no
/// SwiftUI state change anywhere — and the row's height is decided by
/// `MarkdownCodeBlockRepresentable.sizeThatFits`. That the two connect was
/// verified by hand and by nothing else: deleting the invalidation left every
/// other test in this file green, because they call `height(forWidth:)`
/// directly, which is a pure function of state the call does not touch.
@MainActor
@Suite("Preview relayout")
struct PreviewRelayoutTests {

    @Test("Pressing Preview resizes the row in a hosted stack")
    func pressingPreviewResizesTheHostedRow() throws {
        let svg = """
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 300" width="200" height="300">
              <rect width="200" height="300" fill="teal"/>
            </svg>
            """
        let result = MarkdownCompiler().compile("```svg\n\(svg)\n```")
        let host = NSHostingView(
            rootView: MarkdownBlockStack(result: result, options: MarkdownOptions())
        )
        host.frame = NSRect(x: 0, y: 0, width: 400, height: 900)
        host.layoutSubtreeIfNeeded()

        func card() -> MarkdownCodeBlockView? {
            func search(_ view: NSView) -> MarkdownCodeBlockView? {
                if let found = view as? MarkdownCodeBlockView { return found }
                for child in view.subviews {
                    if let found = search(child) { return found }
                }
                return nil
            }
            return search(host)
        }
        let view = try #require(card(), "the code block never mounted")
        let before = view.frame.height
        #expect(before > 0)

        let button = try #require(
            view.subviews.compactMap { $0 as? NSButton }
                .first { $0.accessibilityIdentifier() == "CodeBlock.Preview" }
        )
        _ = button.target?.perform(button.action, with: button)
        host.layoutSubtreeIfNeeded()

        // The frame SwiftUI assigned has to have changed — not merely the
        // number `height(forWidth:)` would return.
        #expect(view.frame.height != before, "the row was never re-measured")
    }

    @Test("Replacing an open preview remeasures its hosted row")
    func replacingOpenPreviewRemeasuresTheHostedRow() throws {
        let wide = """
            <svg xmlns="http://www.w3.org/2000/svg" width="300" height="60" viewBox="0 0 300 60">
              <rect width="300" height="60" fill="teal"/>
            </svg>
            """
        let tall = """
            <svg xmlns="http://www.w3.org/2000/svg" width="100" height="300" viewBox="0 0 100 300">
              <rect width="100" height="300" fill="teal"/>
            </svg>
            """
        let view = MarkdownCodeBlockView(options: MarkdownOptions())
        view.frame = NSRect(x: 0, y: 0, width: 400, height: 200)
        view.configure(code: wide, language: "svg", options: MarkdownOptions())
        let host = NSView(frame: NSRect(x: 0, y: 0, width: 400, height: 900))
        host.addSubview(view)
        host.layoutSubtreeIfNeeded()
        host.needsLayout = false
        let button = try #require(
            view.subviews.compactMap { $0 as? NSButton }
                .first { $0.accessibilityIdentifier() == "CodeBlock.Preview" }
        )
        _ = button.target?.perform(button.action, with: button)
        let before = view.height(forWidth: 400)

        view.configure(code: tall, language: "svg", options: MarkdownOptions())

        #expect(view.height(forWidth: 400) > before)
        #expect(view.intrinsicContentSize.height == view.height(forWidth: view.bounds.width))
        #expect(host.needsLayout)
    }
}
